@server=http://localhost:4004


### Books
# @name Books_GET
GET {{server}}/odata/v4/bookshop-catalog/Books?$expand=author,navCategories($expand=category)


### Books
# @name Books_POST
POST {{server}}/odata/v4/bookshop-catalog/Books
Content-Type: application/json

{
  "ID": "19550310-d892-44ac-9053-1518bb0a5b5c",
  "title": "Harry Potter and the Philosopher's Stone",
  "subtitle": "The beginning of the magical journey",
  "price": 3990,
  "publicationDate": "1997-06-26",
  "stock": 120,
  "rating": 95,
  "available": true,
  "author": {
    "ID": "17448683-bb02-4b93-9892-6822d2c3a839"
  }
}

### Books
# @name Books_POST
POST {{server}}/odata/v4/bookshop-catalog/Books
Content-Type: application/json

{
  "ID": "9e874dc3-1437-4d4d-8f12-ecb219bf5c7f",
  "title": "The Lion, the Witch and the Wardrobe",
  "subtitle": "A timeless adventure in the magical land of Narnia",
  "price": -3590,
  "publicationDate": "1950-10-16",
  "stock": 10,
  "rating": 5,
  "available": true,
  "author": {
    "ID": "51f1a9f2-33f9-4a2f-995a-4f2de4dbb4ad"
  }
}


### Books
# @name Books_POST
POST {{server}}/odata/v4/bookshop-catalog/Books
Content-Type: application/json

{
  "ID": "3e9a4b5f-2c71-4f2e-8d92-91b8a47a9c3d",
  "title": "The Lord of the Rings: The Fellowship of the Ring",
  "subtitle": "The beginning of the epic quest to destroy the One Ring",
  "price": 4990,
  "publicationDate": "1954-07-29",
  "stock": 85,
  "rating": 98,
  "available": true,
  "author_ID": "a7d3e29f-5f48-47cb-9a2c-cc7e1b6d9e32"
}


### Books
# @name Books_PATCH
PATCH {{server}}/odata/v4/bookshop-catalog/Books/19550310-d892-44ac-9053-1518bb0a5b5c
Content-Type: application/json

{
    "subtitle": "The beginning of the magical journey at Hogwarts"
}


### Books
# @name Books_DELETE
DELETE {{server}}/odata/v4/bookshop-catalog/Books/19550310-d892-44ac-9053-1518bb0a5b5c
Content-Type: application/json
