@server=http://localhost:4004


### Customers
# @name Customers_GET
GET {{server}}/odata/v4/bookshop-catalog/Customers


### Customer with Country
# @name Customers_GET
GET {{server}}/odata/v4/bookshop-catalog/Customers?$expand=country


### Customers
# @name Customers_POST
POST {{server}}/odata/v4/bookshop-catalog/Customers
Content-Type: application/json

{
  "ID": "20449002-5143-415c-9eea-eee19b4ce703",
  "firstName": "John",
  "lastName": "Lennon",
  "cpf": "128.878.287-24",
  "phone": "11-99999-8888",
  "address": "Rua ABC",
  "city": "São Paulo",
  "state": "SP",
  "country_code": "BR",
  "cep": "12345-678"
}

### Customers
# @name Customers_POST
PATCH {{server}}/odata/v4/bookshop-catalog/Customers/20449002-5143-415c-9eea-eee19b4ce703
Content-Type: application/json

{
  "country_code": "BR"
}


### Customers
# @name Customers_DELETE
DELETE {{server}}/odata/v4/bookshop-catalog/Customers/20449002-5143-415c-9eea-eee19b4ce703
Content-Type: application/json
