@server=http://localhost:4004


### Customers
# @name Customers_GET
GET {{server}}/odata/v4/bookshop-catalog/Customers


### Customer with Country
# @name Customers_GET
GET {{server}}/odata/v4/bookshop-catalog/Customers?$expand=orders


### Customers
# @name Customers_POST
POST {{server}}/odata/v4/bookshop-catalog/Customers
Content-Type: application/json

{
  "firstName": "Teste",
  "lastName": "Alfa",
  "cpf": "11111111120",
  "phone": "11999887777",
  "address": "Rua DEF",
  "city": "São Paulo",
  "state": "SP",
  "cep": "10300400"
}

### Customers
# @name Customers_POST
PATCH {{server}}/odata/v4/bookshop-catalog/Customers/20449002-5143-415c-9eea-eee19b4ce703
Content-Type: application/json

{
  "country_code": "BR"
}


### Customers
# @name Customers_DELETE
DELETE {{server}}/odata/v4/bookshop-catalog/Customers/20449002-5143-415c-9eea-eee19b4ce703
Content-Type: application/json
