@server=http://localhost:4004


### Orders
# @name Orders_GET
GET {{server}}/odata/v4/bookshop-catalog/Orders



### Orders
# @name Orders_POST
POST {{server}}/odata/v4/bookshop-catalog/Orders
Content-Type: application/json

{
  "customer_ID": "9e836a25-a263-40e2-b2f8-ea63ca96df91",
  "status": "PAID",
  "OrderDate": "2005-09-14T00:00:00.000Z",
  "orderItems": [
    {
      "ID": "27838193-3128-41aa-9343-730625e9ad4b",
      "book_ID": "1288225f-7bb4-4fb0-a9fe-7dcf47aa5bb5",
      "quantity": 2
    }
  ]
}


### Orders
# @name Orders_DELETE
DELETE {{server}}/odata/v4/bookshop-catalog/Orders/21381376-a47c-4529-bbb4-dcce20f0c68d
Content-Type: application/json
