@server=http://localhost:4004
@username=bob
@password=1234

### Orders
# @name Orders_GET
GET {{server}}/odata/v4/bookshop-catalog/Orders
Authorization: Basic {{username}}:{{password}}


### Orders
# @name Orders_POST
POST {{server}}/odata/v4/bookshop-catalog/Orders
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "ID": "21381376-a47c-4529-bbb4-dcce20f0c68d",
  "customer_ID": "20449002-5143-415c-9eea-eee19b4ce703",
  "status": "PAID",
  "OrderDate": "2005-09-14T00:00:00.000Z",
  "orderItems": [
    {
      "book_ID": "2e9fdb64-62ac-4a7f-b75b-4a9e889a5d2e",
      "quantity": 1
    }
  ]
}

### Orders
# @name Orders_POST
POST {{server}}/odata/v4/bookshop-catalog/Orders
Authorization: Basic john:1234
Content-Type: application/json

{
  "ID": "aeff1fb8-2e21-430f-acdc-c80383febcec",
  "customer_ID": "20449002-5143-415c-9eea-eee19b4ce703",
  "status": "PAID",
  "OrderDate": "2005-09-14T00:00:00.000Z",
  "orderItems": [
    {
      "book_ID": "2e9fdb64-62ac-4a7f-b75b-4a9e889a5d2e",
      "quantity": 1
    }
  ]
}


### Orders
# @name Orders_DELETE
DELETE {{server}}/odata/v4/bookshop-catalog/Orders/21381376-a47c-4529-bbb4-dcce20f0c68d
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

