@server=http://localhost:4004


### Orders
# @name Orders_GET
GET {{server}}/odata/v4/bookshop-catalog/Orders?$expand=orderItem($expand=book)



### Orders
# @name Orders_POST
POST {{server}}/odata/v4/bookshop-catalog/Orders
Content-Type: application/json

{
  "ID": "21381376-a47c-4529-bbb4-dcce20f0c68d",
  "OrderDate": "2005-09-14T00:00:00.000Z",
  "status": "status-21381376",
  "orderItems": [
    {
      "ID": "27838192-4bfb-48c3-a488-e4c7123f81ef",
      "book_ID": "19550310-d892-44ac-9053-1518bb0a5b5c",
      "quantity": 1
    },
    {
      "ID": "27838193-3128-41aa-9343-730625e9ad4b",
      "book_ID": "3e9a4b5f-2c71-4f2e-8d92-91b8a47a9c3d",
      "quantity": 2
    }
  ]
}


### Orders
# @name Orders_DELETE
DELETE {{server}}/odata/v4/bookshop-catalog/Orders/21381376-a47c-4529-bbb4-dcce20f0c68d
Content-Type: application/json
